# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bramplot.ui'
#
# Created: Wed Mar 06 15:57:14 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from mplZoomWidget import MatplotlibZoomWidget

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(908, 661)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 763, 599))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mplwidget = MatplotlibZoomWidget(self.layoutWidget)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.verticalLayout.addWidget(self.mplwidget)
        self.mplwidget_2 = MatplotlibZoomWidget(self.layoutWidget)
        self.mplwidget_2.setObjectName(_fromUtf8("mplwidget_2"))
        self.verticalLayout.addWidget(self.mplwidget_2)
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(780, 10, 121, 20))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(780, 35, 121, 20))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(780, 200, 120, 80))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.bodeplot = QtGui.QRadioButton(self.groupBox)
        self.bodeplot.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.bodeplot.setText(QtGui.QApplication.translate("MainWindow", "Bode Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.bodeplot.setChecked(True)
        self.bodeplot.setObjectName(_fromUtf8("bodeplot"))
        self.quantumwire = QtGui.QRadioButton(self.groupBox)
        self.quantumwire.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.quantumwire.setText(QtGui.QApplication.translate("MainWindow", "Quantum Wire", None, QtGui.QApplication.UnicodeUTF8))
        self.quantumwire.setObjectName(_fromUtf8("quantumwire"))
        self.tempsweep = QtGui.QRadioButton(self.groupBox)
        self.tempsweep.setGeometry(QtCore.QRect(10, 60, 121, 17))
        self.tempsweep.setText(QtGui.QApplication.translate("MainWindow", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.tempsweep.setObjectName(_fromUtf8("tempsweep"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(780, 70, 120, 121))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.he3Button = QtGui.QRadioButton(self.groupBox_2)
        self.he3Button.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.he3Button.setText(QtGui.QApplication.translate("MainWindow", "He3", None, QtGui.QApplication.UnicodeUTF8))
        self.he3Button.setChecked(True)
        self.he3Button.setObjectName(_fromUtf8("he3Button"))
        self.vtiButton = QtGui.QRadioButton(self.groupBox_2)
        self.vtiButton.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.vtiButton.setText(QtGui.QApplication.translate("MainWindow", "VTI", None, QtGui.QApplication.UnicodeUTF8))
        self.vtiButton.setObjectName(_fromUtf8("vtiButton"))
        self.dilutionButton = QtGui.QRadioButton(self.groupBox_2)
        self.dilutionButton.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.dilutionButton.setText(QtGui.QApplication.translate("MainWindow", "Dilution", None, QtGui.QApplication.UnicodeUTF8))
        self.dilutionButton.setObjectName(_fromUtf8("dilutionButton"))
        self.customButton = QtGui.QRadioButton(self.groupBox_2)
        self.customButton.setGeometry(QtCore.QRect(10, 80, 82, 17))
        self.customButton.setText(QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.customButton.setObjectName(_fromUtf8("customButton"))
        self.debugButton = QtGui.QRadioButton(self.groupBox_2)
        self.debugButton.setGeometry(QtCore.QRect(10, 100, 82, 17))
        self.debugButton.setText(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.debugButton.setObjectName(_fromUtf8("debugButton"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(780, 310, 120, 80))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Top Plot Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.xlist1 = QtGui.QComboBox(self.groupBox_3)
        self.xlist1.setGeometry(QtCore.QRect(40, 20, 71, 20))
        self.xlist1.setObjectName(_fromUtf8("xlist1"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 20, 31, 20))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "x-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 29, 20))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ylist1 = QtGui.QComboBox(self.groupBox_3)
        self.ylist1.setGeometry(QtCore.QRect(40, 50, 71, 20))
        self.ylist1.setObjectName(_fromUtf8("ylist1"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(780, 400, 120, 80))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Bottom Plot Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 29, 16))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "x-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 29, 16))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.xlist2 = QtGui.QComboBox(self.groupBox_4)
        self.xlist2.setGeometry(QtCore.QRect(40, 20, 69, 20))
        self.xlist2.setObjectName(_fromUtf8("xlist2"))
        self.ylist2 = QtGui.QComboBox(self.groupBox_4)
        self.ylist2.setGeometry(QtCore.QRect(40, 50, 69, 20))
        self.ylist2.setObjectName(_fromUtf8("ylist2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

