# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fridgemonitor.ui'
#
# Created: Fri Jan 11 07:48:03 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FridgeMonitorWindow(object):
    def setupUi(self, FridgeMonitorWindow):
        FridgeMonitorWindow.setObjectName(_fromUtf8("FridgeMonitorWindow"))
        FridgeMonitorWindow.resize(1031, 621)
        FridgeMonitorWindow.setWindowTitle(QtGui.QApplication.translate("FridgeMonitorWindow", "Thermometry", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(FridgeMonitorWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget.sizePolicy().hasHeightForWidth())
        self.mplwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.mplwidget.setFont(font)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.gridLayout.addWidget(self.mplwidget, 0, 0, 1, 1)
        self.mplwidget_2 = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_2.sizePolicy().hasHeightForWidth())
        self.mplwidget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.mplwidget_2.setFont(font)
        self.mplwidget_2.setObjectName(_fromUtf8("mplwidget_2"))
        self.gridLayout.addWidget(self.mplwidget_2, 0, 1, 1, 1)
        self.mplwidget_3 = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_3.sizePolicy().hasHeightForWidth())
        self.mplwidget_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.mplwidget_3.setFont(font)
        self.mplwidget_3.setObjectName(_fromUtf8("mplwidget_3"))
        self.gridLayout.addWidget(self.mplwidget_3, 1, 0, 1, 1)
        self.mplwidget_4 = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_4.sizePolicy().hasHeightForWidth())
        self.mplwidget_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.mplwidget_4.setFont(font)
        self.mplwidget_4.setObjectName(_fromUtf8("mplwidget_4"))
        self.gridLayout.addWidget(self.mplwidget_4, 1, 1, 1, 1)
        self.mplwidget_5 = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_5.sizePolicy().hasHeightForWidth())
        self.mplwidget_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.mplwidget_5.setFont(font)
        self.mplwidget_5.setObjectName(_fromUtf8("mplwidget_5"))
        self.gridLayout.addWidget(self.mplwidget_5, 2, 0, 1, 1)
        self.mplwidget_6 = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_6.sizePolicy().hasHeightForWidth())
        self.mplwidget_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.mplwidget_6.setFont(font)
        self.mplwidget_6.setObjectName(_fromUtf8("mplwidget_6"))
        self.gridLayout.addWidget(self.mplwidget_6, 2, 1, 1, 1)
        self.mplwidget_7 = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_7.sizePolicy().hasHeightForWidth())
        self.mplwidget_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.mplwidget_7.setFont(font)
        self.mplwidget_7.setObjectName(_fromUtf8("mplwidget_7"))
        self.gridLayout.addWidget(self.mplwidget_7, 3, 0, 1, 1)
        self.mplwidget_8 = MatplotlibWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_8.sizePolicy().hasHeightForWidth())
        self.mplwidget_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.mplwidget_8.setFont(font)
        self.mplwidget_8.setObjectName(_fromUtf8("mplwidget_8"))
        self.gridLayout.addWidget(self.mplwidget_8, 3, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fileNameLabel = QtGui.QLabel(self.centralwidget)
        self.fileNameLabel.setText(QtGui.QApplication.translate("FridgeMonitorWindow", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNameLabel.setObjectName(_fromUtf8("fileNameLabel"))
        self.horizontalLayout.addWidget(self.fileNameLabel)
        self.fileNameLineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNameLineEdit.sizePolicy().hasHeightForWidth())
        self.fileNameLineEdit.setSizePolicy(sizePolicy)
        self.fileNameLineEdit.setObjectName(_fromUtf8("fileNameLineEdit"))
        self.horizontalLayout.addWidget(self.fileNameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.startStopButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startStopButton.sizePolicy().hasHeightForWidth())
        self.startStopButton.setSizePolicy(sizePolicy)
        self.startStopButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.startStopButton.setText(QtGui.QApplication.translate("FridgeMonitorWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.startStopButton.setObjectName(_fromUtf8("startStopButton"))
        self.verticalLayout.addWidget(self.startStopButton)
        self.alarmCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.alarmCheckBox.setText(QtGui.QApplication.translate("FridgeMonitorWindow", "Send text messages", None, QtGui.QApplication.UnicodeUTF8))
        self.alarmCheckBox.setObjectName(_fromUtf8("alarmCheckBox"))
        self.verticalLayout.addWidget(self.alarmCheckBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.htrOutputLabel = QtGui.QLabel(self.centralwidget)
        self.htrOutputLabel.setText(QtGui.QApplication.translate("FridgeMonitorWindow", "Heater output:", None, QtGui.QApplication.UnicodeUTF8))
        self.htrOutputLabel.setObjectName(_fromUtf8("htrOutputLabel"))
        self.horizontalLayout_3.addWidget(self.htrOutputLabel)
        self.htrOutputLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.htrOutputLineEdit.setObjectName(_fromUtf8("htrOutputLineEdit"))
        self.horizontalLayout_3.addWidget(self.htrOutputLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.htrRangeLabel = QtGui.QLabel(self.centralwidget)
        self.htrRangeLabel.setText(QtGui.QApplication.translate("FridgeMonitorWindow", "Heater Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeLabel.setObjectName(_fromUtf8("htrRangeLabel"))
        self.horizontalLayout_2.addWidget(self.htrRangeLabel)
        self.htrRangeComboBox = QtGui.QComboBox(self.centralwidget)
        self.htrRangeComboBox.setObjectName(_fromUtf8("htrRangeComboBox"))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(0, QtGui.QApplication.translate("FridgeMonitorWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(1, QtGui.QApplication.translate("FridgeMonitorWindow", "31.6 uA", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(2, QtGui.QApplication.translate("FridgeMonitorWindow", "100 uA", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(3, QtGui.QApplication.translate("FridgeMonitorWindow", "316 uA", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(4, QtGui.QApplication.translate("FridgeMonitorWindow", "1.00 mA", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(5, QtGui.QApplication.translate("FridgeMonitorWindow", "3.16 mA", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(6, QtGui.QApplication.translate("FridgeMonitorWindow", "10.0 mA", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(7, QtGui.QApplication.translate("FridgeMonitorWindow", "31.6 mA", None, QtGui.QApplication.UnicodeUTF8))
        self.htrRangeComboBox.addItem(_fromUtf8(""))
        self.htrRangeComboBox.setItemText(8, QtGui.QApplication.translate("FridgeMonitorWindow", "100 mA", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_2.addWidget(self.htrRangeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        FridgeMonitorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(FridgeMonitorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        FridgeMonitorWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(FridgeMonitorWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        FridgeMonitorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FridgeMonitorWindow)
        QtCore.QMetaObject.connectSlotsByName(FridgeMonitorWindow)

    def retranslateUi(self, FridgeMonitorWindow):
        pass

from matplotlibwidget import MatplotlibWidget
